heat_template_version: 2017-02-24

description: pFinalCNVR - APP

parameters:

  server_name:
    type: string
    description: Server name

  flavor:
    type: string
    description: Instance resources (flavor)
    default: m1.smaller
    constraints:
      - allowed_values: [m1.nano, m1.tiny, m1.small, m1.smaller, m1.large]
        description: Value must be one of m1.tiny, m1.small, m1.smaller or m1.large

  image:
    type: string
    default: xenial-server-cloudimg-amd64-vnx
    description: Image name

  net1_name: 
    type: string 
    description: Net 1 name

  subnet1_name: 
    type: string 
    description: Subnet 1 name

  net2_name: 
    type: string 
    description: Net 2 name

  subnet2_name: 
    type: string 
    description: Subnet 2 name

resources:

  app_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_file: cloud-init/app_1_config.yaml }
      networks:
        - port: { get_resource: app_server_port0 }
        - port: { get_resource: app_server_port1 }

  app_server_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net1_name }
      security_groups:
        - open
      fixed_ips:
        - subnet_id: { get_param: subnet1_name }

  app_server_port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net2_name }
      security_groups:
        - open
      fixed_ips:
        - subnet_id: { get_param: subnet2_name }

outputs:

  app_server:
    description: App server outputs
    value: { get_attr: [ app_server, networks, { get_param: net1_name }, 0 ] }
