heat_template_version: 2017-02-24

description: App servers deployment template

parameters:

  server_name:
    type: string
    description: Nombre del servidor

  flavor:
    type: string
    description: Flavor de la instancia
    default: m1.smaller
    constraints:
      - allowed_values: [m1.nano, m1.tiny, m1.small, m1.smaller, m1.large]
        description: Value must be one of m1.tiny, m1.small, m1.smaller or m1.large

  image:
    type: string
    default: xenial-server-cloudimg-amd64-vnx
    description: Nombre de la imagen

  private_net_name: 
    type: string 
    description: Nombre de la red privada 1

  private_subnet_name: 
    type: string 
    description: Nombre de la subred privada 1

  private_net_2_name: 
    type: string 
    description: Nombre de la red privada 2

  private_subnet_2_name: 
    type: string 
    description: Nombre de la subred privada 2

resources:

  app_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_file: cloud-init/app_1_config.yaml }
      networks:
        - port: { get_resource: app_server_port0 }
        - port: { get_resource: app_server_port1 }

  app_server_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_name }
      security_groups:
        - open
      fixed_ips:
        - subnet_id: { get_param: private_subnet_name }

  app_server_port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_2_name }
      security_groups:
        - open
      fixed_ips:
        - subnet_id: { get_param: private_subnet_2_name }

outputs:

  app_server:
    description: Atributos del servidor de aplicaciones
    value: { get_attr: [ app_server, networks, { get_param: private_net_name }, 0 ] }
