heat_template_version: 2017-02-24

description: pFinalCNVR - DB 

parameters:

  server_name:
    type: string
    description: Server name 

  flavor:
    type: string
    description: Instance resources (flavor)
    default: m1.smaller
    constraints:
      - allowed_values: [m1.nano, m1.tiny, m1.smaller]
        description: Value must be one of m1.nano, m1.tiny, m1.smaller

  image:
    type: string
    default: db-image
    description: Image name

  net2_name: 
    type: string 
    description: Net 2 name

  subnet2_name: 
    type: string 
    description: Subnet 2 name

  private_ip_address:
    type: string
    description: Assigned IP addr

resources:

  db_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_file: cloud-init/db.yaml }
      networks:
        - port: { get_resource: db_server_port0 }

  db_server_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net2_name }
      security_groups:
        - open
      fixed_ips:
        - subnet_id: { get_param: subnet2_name }
          ip_address: { get_param: private_ip_address }

outputs:
  first_address:
    description: DB private IP addr
    value: { get_attr: [ db_server, first_address ] }
