parameters:
  net1_name: Net1
  subnet1_name: subnet1
  subnet1_prefix: 10.100.0.0/24
  subnet1_gateway: 10.100.0.1
  net2_name: Net2
  subnet2_name: subnet2
  subnet2_prefix: 10.200.0.0/24
  extnet_name: ExtNet
  db_ip_address: 10.200.0.3
