#cloud-config
hostname: admin
runcmd:
        - ifconfig ens4 up
        - dhclient ens4
        - echo "nameserver 8.8.8.8 " > /etc/resolv.conf
        - "sed -i '/Port 22/c\Port 2222' /etc/ssh/sshd_config"
        - service sshd restart 
